import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Client from "@/shared/layout/client";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const trajan = localFont({
  src: "./fonts/Trajan-Pro.otf",
  variable: "--font-trajan",
  weight: "100 900",
});

const soleSans = localFont({
  src: "./fonts/SoleSans-Regular.woff",
  variable: "--font-sole-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Base Landing",
  description: "Generated by Jee",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${trajan.variable} ${soleSans.variable}`}
      >
        <Client>{children}</Client>
      </body>
    </html>
  );
}
